# -*- coding: utf-8 -*-
"""
/***************************************************************************
 switchactivelayer
                                 A QGIS plugin
 Keyboard shortcut to change active layer up or down in legend.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-15
        copyright            : (C) 2022 by Thomas Ailhaud - SDIS 04
        email                : tailhaud@sdis04.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load switchactivelayer class from file switchactivelayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .switch_active_layer import switchactivelayer
    return switchactivelayer(iface)
